### ISSUE TITLE
`-f` option makes an error

### ISSUE THREAD

**Issue by yayamamo** [pubannotation/pubtator-to-pubannotation#2]
Using `-f` option raised the following error, which didn't happen without the option.
```
$ ./pubtator-to-pubannotation.rb -f  output/BioCXML/10.BioC.XML
The output will be stored in the directory, 'output'.
processing output/BioCXML/10.BioC.XML
./pubtator-to-pubannotation.rb:81:in `get_adjustment': undefined method `rindex' for nil:NilClass (NoMethodError)

        r = window.rindex(lex)
                  ^^^^^^^
        from ./pubtator-to-pubannotation.rb:45:in `block (3 levels) in PubTatorBioC_to_PubAnnotationJSON'
        from ./pubtator-to-pubannotation.rb:27:in `each'
        from ./pubtator-to-pubannotation.rb:27:in `block (2 levels) in PubTatorBioC_to_PubAnnotationJSON'
        from ./pubtator-to-pubannotation.rb:18:in `each'
        from ./pubtator-to-pubannotation.rb:18:in `block in PubTatorBioC_to_PubAnnotationJSON'
        from ./pubtator-to-pubannotation.rb:15:in `each'
        from ./pubtator-to-pubannotation.rb:15:in `PubTatorBioC_to_PubAnnotationJSON'
        from ./pubtator-to-pubannotation.rb:143:in `block in process_xml_content'
        from ./pubtator-to-pubannotation.rb:142:in `open'
        from ./pubtator-to-pubannotation.rb:142:in `process_xml_content'
        from ./pubtator-to-pubannotation.rb:176:in `block in <main>'
        from ./pubtator-to-pubannotation.rb:158:in `each'
        from ./pubtator-to-pubannotation.rb:158:in `<main>'
```

**Comment by jdkim** [comment]
exception handlingを改善しました。テストはしてないですが、多分治ってるかと思います。
該当のファイルの10.BioC.XMLがどのtar.gzファイルにあるか教えて下さるとテストもしてみます。

**Comment by yayamamo** [comment]
ありがとうございます。
動作確認できました。

ファイルは、`ftp://ftp.ncbi.nlm.nih.gov/pub/lu/PubTator3/` から取得した `BioCXML.0.tar.gz` に含まれているものです。

**Comment by yayamamo** [comment]
問題なさそうなので、クローズします。
