### ISSUE TITLE
Working around invalid xml files.

### ISSUE THREAD

**Issue by yayamamo** [pubannotation/pubtator-to-pubannotation#3]
下記のエラーが生じました。
これは恐らく `71500.BioC.XML` の問題だと思いますが、このような入力に対してエラー終了しないような対策をしておくと良いと思います。
```
processing output/BioCXML/71500.BioC.XML
./pubtator-to-pubannotation.rb:14:in `parse': invalid format, elements overlap at line 102, column 14 [parse.c:605] (Ox::ParseError)
        from ./pubtator-to-pubannotation.rb:14:in `PubTatorBioC_to_PubAnnotationJSON'
        from ./pubtator-to-pubannotation.rb:146:in `block in process_xml_content'
        from ./pubtator-to-pubannotation.rb:145:in `open'
        from ./pubtator-to-pubannotation.rb:145:in `process_xml_content'
        from ./pubtator-to-pubannotation.rb:172:in `block (4 levels) in <main>'
        from /home/yayamamo/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:65:in `each'
        from ./pubtator-to-pubannotation.rb:166:in `block (3 levels) in <main>'
        from /home/yayamamo/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:25:in `new'
        from ./pubtator-to-pubannotation.rb:165:in `block (2 levels) in <main>'
        from ./pubtator-to-pubannotation.rb:164:in `open'
        from ./pubtator-to-pubannotation.rb:164:in `block in <main>'
        from ./pubtator-to-pubannotation.rb:161:in `each'
        from ./pubtator-to-pubannotation.rb:161:in `<main>'
```

**Comment by yayamamo** [comment]
これまで、以下のファイル処理中にエラー終了しています。
`BioCXML.0.tar.gz` の `71500.BioC.XML`、
`BioCXML.1.tar.gz` の `71501.BioC.XML`、
`BioCXML.2.tar.gz` の `71502.BioC.XML`。

**Comment by yayamamo** [comment]
`BioCXML.5.tar.gz` の `37065.BioC.XML` では、以下のエラーがありました。
```
pubtator-to-pubannotation.rb:84:in `rindex': no implicit conversion of nil into String (TypeError)

        r = window&.rindex(lex)
                           ^^^
        from pubtator-to-pubannotation.rb:84:in `get_adjustment'
        from pubtator-to-pubannotation.rb:45:in `block (3 levels) in PubTatorBioC_to_PubAnnotationJSON'
        from pubtator-to-pubannotation.rb:27:in `each'
        from pubtator-to-pubannotation.rb:27:in `block (2 levels) in PubTatorBioC_to_PubAnnotationJSON'
        from pubtator-to-pubannotation.rb:18:in `each'
        from pubtator-to-pubannotation.rb:18:in `block in PubTatorBioC_to_PubAnnotationJSON'
        from pubtator-to-pubannotation.rb:15:in `each'
        from pubtator-to-pubannotation.rb:15:in `PubTatorBioC_to_PubAnnotationJSON'
        from pubtator-to-pubannotation.rb:146:in `block in process_xml_content'
        from pubtator-to-pubannotation.rb:145:in `open'
        from pubtator-to-pubannotation.rb:145:in `process_xml_content'
        from pubtator-to-pubannotation.rb:172:in `block (4 levels) in <main>'
        from /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
        from pubtator-to-pubannotation.rb:166:in `block (3 levels) in <main>'
        from /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:25:in `new'
        from pubtator-to-pubannotation.rb:165:in `block (2 levels) in <main>'
        from pubtator-to-pubannotation.rb:164:in `open'
        from pubtator-to-pubannotation.rb:164:in `block in <main>'
        from pubtator-to-pubannotation.rb:161:in `each'
        from pubtator-to-pubannotation.rb:161:in `<main>'
```

**Comment by yayamamo** [comment]
`BioCXML.6.tar.gz` の `41006.BioC.XML` では、以下のエラーがありました。
```
/usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader/entry.rb:166:in `read': invalid stored block lengths (Zlib::DataError)
        from /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader/entry.rb:166:in `read'
        from pubtator-to-pubannotation.rb:171:in `block (4 levels) in <main>'
        from /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:65:in `each'
        from pubtator-to-pubannotation.rb:166:in `block (3 levels) in <main>'
        from /usr/local/lib/ruby/3.3.0/rubygems/package/tar_reader.rb:25:in `new'
        from pubtator-to-pubannotation.rb:165:in `block (2 levels) in <main>'
        from pubtator-to-pubannotation.rb:164:in `open'
        from pubtator-to-pubannotation.rb:164:in `block in <main>'
        from pubtator-to-pubannotation.rb:161:in `each'
        from pubtator-to-pubannotation.rb:161:in `<main>'
```

**Comment by jdkim** [comment]
Exception handlingを追加したバージョンをpushしました。
-fs オプションを付けて使ってください。
まだテストが十分行ってないです。時間がかかりますので、とりあえずpushします。
